### ISSUE TITLE
HTTP Control help

### ISSUE THREAD

**Issue by yajrendrag** [maddox/harmony-api#10]
server installed fine, running in development mode.
i can issue GET to get status and activities and hub responds properly.
trying to issue POST from postman - http://localhost:8282/start_activity?activity=watch-tv

responds with:

```
{
  "message": "Not Found"
}
```

(also, your README shows /start_activity?activity=, but when i connect to localhost:8282, the web page displays /start_activity?activity_name=.  This isn't my problem as both of these yield same result as shown above.)

are there any headers required or any other suggestions?

**Comment by maddox** [comment]
> also, your README shows /start_activity?activity=, but when i connect to localhost:8282, the web page displays /start_activity?activity_name=.

This was actually incorrect, thanks! I fixed this.

**Comment by maddox** [comment]
If you're getting that message in the resulting JSON, you're getting a `404`. You're getting a `404` because the activity you're providing was not found. You might want to check your format again. It's using the slug of the activity. Check the slug name of the activity you're trying to trigger by checking the results of the `GET` on `/status`.
