### ISSUE TITLE
Can no longer find hub

### ISSUE THREAD

**Issue by matt-teix** [maddox/harmony-api#101]
I had this running previously for a couple of months without any issues. Recently it stopped work and found it to no longer find my hub. Ive Verified my network settings and even reset the router and the hub. Ive reinstalled the Harmony-api image and still no luck, i even attmepted to add the hub ip to the config but it still doesnt appear. Any tips or tricks to get this running again would be great.

**Comment by vslavik** [comment]
Complain to Logitech — they removed local control of the Hub in a recent firmware update: https://www.reddit.com/r/homeassistant/comments/a6u6ep/psa_harmony_hub_firmware_v415206_breaksremoves/

**Comment by matt-teix** [comment]
I was afraid of that, that’s for the information tho

**Comment by cmon69** [comment]
> 
> 
> Complain to Logitech — they removed local control of the Hub in a recent firmware update: https://www.reddit.com/r/homeassistant/comments/a6u6ep/psa_harmony_hub_firmware_v415206_breaksremoves/

The link you provided helped me to correct the issue THANKS!

**Comment by cmon69** [comment]
From Ruricu

Successfully downgraded my hub to 4.15.193 and restored API access. Full repro:

1 Launch MyHarmony app on PC.

2 Press Alt+F9 to open the advanced tools menu

3 Scroll the window to find your Harmony model.

4 Select "Factory Reset" for the appropriate model. This does not do anything immediately.

5 Steps 1-4 will be displayed for completing a Factory Reset. We are only doing Step 1. "Restore" here means "Rollback".

6 Connect your Harmony hub to the PC via micro-USB.

7 Within a few minutes, it will be detected by MyHarmony and display Remote Model, Firmware Version, and Hardware revision. The Restore button will be enabled.

8 Click "Restore" and wait. (Now is the first time that it actually describes that it's a rollback!)

9 When it completes, you should be on Firmware Version 4.15.193. Disconnect the hub from the PC and return it to its original location.

And the final, important step: eliminate the ability for the Harmony hub to access these domains (svcs.myharmony.com pubsub.pubnub.com content.dhg.myharmony.com logging.dhg.myharmony.com myharmony.com sus.dhg.myharmony.com), or the internet altogether. I used DD-WRT's Access Restrictions feature to disable all internet access, because my specific implementation is entirely intranet-based. YMMV.

**Comment by 1iveowl** [comment]
Harmony hub seem to still be accessable using Websocket instead of XMPP. 

Any considerations on adopting this approach instead?

**Comment by matt-teix** [comment]
You can’t resync your devices tho correct? Need to setup as a new device?

**Comment by maddox** [comment]
Hi everyone. Unfortunately Logitech has decided to close the local API available on the hub.

https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities

This means you should either downgrade, or find another means to control your media stuff. Home assistant has a patch out to switch to the new found API, if you use Home Assistant, I suggest you switch that from Harmony API.

This effectively ends Harmony API. I'll write a note on the README later today. Thanks for everyone's support!

**Comment by svenove** [comment]
Logitech has changed their mind!
https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities

Update to beta .210 to restore XMPP and harmony-api should start working again. :)
