### ISSUE TITLE
Multiple Hubs?

### ISSUE THREAD

**Issue by jer78** [maddox/harmony-api#17]
I just started using this for Home Assistant and it seems to pull activities from both of my harmony hubs but for some reason only update 1 of them. Is the multiple hubs coming soon?? Looking forward to testing if you need anyone to help. Thanks again for all of your work! This is really great!

**Comment by maddox** [comment]
It's never been used with multiple hubs, as I don't have multiple hubs.

Interesting that it pulls activities for all of the hubs. It's totally understandable that it'd only set one hub though, as it assumes a single hub.

**Comment by jer78** [comment]
Thanks Maddox for your quick reply. Any chance we can get you a second harmony hub?? ;) 

I was using a plugin for homebridge that does multiple hubs except it crashes a lot. Not sure if there's something useful if you were to add it down the road. Thanks for your help!

https://github.com/KraigM/homebridge-harmonyhub/tree/develop?files=1

**Comment by maddox** [comment]
Ahh I see. In the [discovery phase](https://github.com/maddox/harmony-api/blob/master/app.js#L59), it just calls `startProcessing` on every hub that is discovered.

But when it runs a command, it [uses](https://github.com/maddox/harmony-api/blob/master/app.js#L102) the `harmonyHubClient`, which is just the last harmony hub found, because of the way it's assigned.

This isn't so simple to fix since the concept of multiple hubs has to be built in, as well as new routes that support name spacing.

It's hard for me to even do this because I don't have multiple hubs.

**Comment by maddox** [comment]
> Thanks Maddox for your quick reply. Any chance we can get you a second harmony hub??

Sure. Email me at the address on my GitHub account and we can figure it out.

**Comment by maddox** [comment]
@jer78 checkout #22. Go ahead and pull and switch to the multiple-hubs branch and see how well this work. Check the README to see how the topics and endpoints have changed.

I'm going to try living on this for little while before publishing. It'd be nice if other people did too.

**Comment by jer78** [comment]
AMAZING!!!! It works beautifully now! Finally have a great solution for Home Assistant and Homebridge. I can't thank you enough!! I'll keep testing and let you know if there any issues, but so far so good!

**Comment by maddox** [comment]
awesome! Give it a good go. If all is well, I'll merge it tonight and put out 2.0. Thanks!

**Comment by jer78** [comment]
Everything is good on my end. No crashes, works like a charm. I'd say merge it! :)

**Comment by maddox** [comment]
great, thanks for your help testing, and sending over a hub to make it happen!

**Comment by jer78** [comment]
My pleasure! I'm happy to help contribute. Thanks for your hard work
